# Author: Daniele Rondina <geaaru@gmail.com>
# Task Cleane
name: "Maintenance - Clean old tasks/pipeline"
image: "macaroni/terragon-minimal"

# The mcli storage contains a script that initialize the Mottainai profile
# used to call Mottainai API.
storage: "mcli"
storage_path: "confs"
entrypoint:
- /bin/sh
- "-c"
source: "https://github.com/MottainaiCI/specs-catalog.git"
directory: "/tasks/infra"
script:
- sleep 1
- anise install --sync-repos dev-util/mottainai-cli utils/jq dev-lang-3.9/python
- mkdir -p /root/.config/
- /bin/bash confs/setup-mcli.sh
- echo "=================================================================="
- export MOTTAINAI_CLI_PROFILE=funtoo
- echo "Clean old tasks:"
- scripts/tasks_cleaner.sh
- echo "=================================================================="
planned: "@daily"
environment:
- RETENTION_PERIOD=5
- LC_ALL=en_US.UTF-8
- LUET_YES=true
- LUET_LOGGING__COLOR=false
- LUET_LOGGING__EMOJI=false
type: lxd
